name: Create Release with Compressed Directory

on:
  push:
    tags:
      - 'v*'  # 태그를 푸시할 때 릴리즈 생성

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
    - name: Compress the directory
      run: |
        mkdir -p artifacts
        zip -r artifacts/rm2k-lostsaga.zip rm2k-lostsaga 
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload compressed file to release
      uses: actions/upload-release-asset@v1
      with:
        release_id: ${{ steps.create_release.outputs.id }}
        asset_path: artifacts/rm2k-lostsaga.zip
        asset_name: rm2k-lostsaga.zip
        asset_content_type: application/zip
