name: Add Asset to Existing Release

on:
  push:
    tags:
      - 'v*'  # 태그를 푸시할 때 릴리즈에 추가

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Compress the directory
      run: |
        mkdir -p artifacts
        zip -r artifacts/rm2k-lostsaga.zip rm2k-lostsaga
    - name: Upload zip to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: artifacts/rm2k-lostsaga.zip
        asset_name: rm2k-lostsaga.zip
        tag: ${{ github.ref }}
